### ISSUE TITLE
Support for directory names with spaces

### ISSUE THREAD

**Issue by soumikpatel** [cdaf/cdaf.github.io#4]
Unable to handle directory names with spaces

**Comment by cdaf** [comment]
Planned for release 2.5.8

**Comment by cdaf** [comment]
Had to bump this, now planned for 2.6.3

**Comment by cdaf** [comment]
This has now been addressed in the release of 2.6.3 http://cdaf.io/

2.6.3 : 26-Jun-2023 : Paths with Spaces

Support for paths with spaces
Make uppercase variables, "Global" variables (replace build.properties in (Linux)
Consistent handling of Environment variables
Support for custom ciProcess in entry
Update GitLab runner after tag CLI deprecation
Remove install packages from /solution of CDAF image
Windows Container support after DockerMsftProvider deprecation (Windows)
